name: Create Docker image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nodebackend:latest


  deploy:
    runs-on: [aws-ec2]
    needs: build
    steps:
      - name: Install Docker
        run: |
          if ! docker --version; then
            sudo yum update -y
            sudo yum install -y docker
            sudo service docker start
            sudo usermod -a -G docker ec2-user
          else
            echo "Docker already installed"
          fi

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
    

      - name: Pull image from docker hub
        run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/nodebackend:latest
      - name: Delete existing container
        run: docker rm -f nodebackend || true
      - name: Run container
        run: docker run -d -p 5000:5000 --name nodebackend ${{ secrets.DOCKER_HUB_USERNAME }}/nodebackend:latest -e MONGO_ATLAS_URL=${{ secrets.MONGO_ATLAS_URL }}
